engines:
  rubocop:
    enabled: true
    exclude_paths:
    - "vendor/"
    - "db/"
    checks:
      Rubocop/Style/Documentation:
        enabled: false

exclude_paths:
- "public/assets/"
- "db/"

ratings:
   paths:
   - "app/**/*"
   - "lib/**/*"
